"""add location events table

Revision ID: 625c67ffd123
Revises: fa945ad9fe85
Create Date: 2026-04-17 14:13:04.278332

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '625c67ffd123'
down_revision: Union[str, Sequence[str], None] = 'fa945ad9fe85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('place_name', sa.String(length=512), nullable=True),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('geo_source', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['raw_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_location_events_document_id', 'location_events', ['document_id'], unique=False)
    op.create_index('ix_location_events_entity_id', 'location_events', ['entity_id'], unique=False)
    op.create_index('ix_location_events_geo_source', 'location_events', ['geo_source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_location_events_geo_source', table_name='location_events')
    op.drop_index('ix_location_events_entity_id', table_name='location_events')
    op.drop_index('ix_location_events_document_id', table_name='location_events')
    op.drop_table('location_events')
    # ### end Alembic commands ###
