"""initial schema: sources, raw_documents, entities, mentions

Revision ID: fa945ad9fe85
Revises: 
Create Date: 2026-04-16 11:02:48.229300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa945ad9fe85'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_name', sa.String(length=512), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_entities_canonical_name', 'entities', ['canonical_name'], unique=False)
    op.create_index('ix_entities_confidence', 'entities', ['confidence'], unique=False)
    op.create_index('ix_entities_entity_type', 'entities', ['entity_type'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sources_active', 'sources', ['active'], unique=False)
    op.create_index('ix_sources_type', 'sources', ['type'], unique=False)
    op.create_table('raw_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash', name='uq_raw_documents_url_hash')
    )
    op.create_index('ix_raw_documents_fetched_at', 'raw_documents', ['fetched_at'], unique=False)
    op.create_index('ix_raw_documents_processing_status', 'raw_documents', ['processing_status'], unique=False)
    op.create_index('ix_raw_documents_source_id', 'raw_documents', ['source_id'], unique=False)
    op.create_table('mentions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['raw_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mentions_document_id', 'mentions', ['document_id'], unique=False)
    op.create_index('ix_mentions_entity_id', 'mentions', ['entity_id'], unique=False)
    op.create_index('ix_mentions_score', 'mentions', ['score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mentions_score', table_name='mentions')
    op.drop_index('ix_mentions_entity_id', table_name='mentions')
    op.drop_index('ix_mentions_document_id', table_name='mentions')
    op.drop_table('mentions')
    op.drop_index('ix_raw_documents_source_id', table_name='raw_documents')
    op.drop_index('ix_raw_documents_processing_status', table_name='raw_documents')
    op.drop_index('ix_raw_documents_fetched_at', table_name='raw_documents')
    op.drop_table('raw_documents')
    op.drop_index('ix_sources_type', table_name='sources')
    op.drop_index('ix_sources_active', table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_entities_entity_type', table_name='entities')
    op.drop_index('ix_entities_confidence', table_name='entities')
    op.drop_index('ix_entities_canonical_name', table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
